kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-foobar
spec:
  podSelector:
    matchLabels:
      foo: bar
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access: "true"
